# Generated by Django 3.2.25 on 2026-10-04 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='f06f53d9-7799-41aa-baa9-6c12225d98ac', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved')], max_length=20)),
                ('to_status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cms.content')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
