# Generated by Django 3.2.25 on 2026-10-05 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20261004_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Content Manager'), ('writer', 'Content Writer')], default='writer', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='a400ac10-da96-459e-a521-c1958e1c1209', max_length=500, null=True),
        ),
        migrations.RunSQL(
            "UPDATE cms_user SET role = 'manager' WHERE role = 'admin'",
            "UPDATE cms_user SET role = 'admin' WHERE role = 'manager'",
        ),
    ]
